source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/darkThanBlack/Specs.git'

workspace 'ProjectName.xcworkspace'

use_frameworks!

platform :ios, '12.0'

target 'ProjectName' do
  platform :ios, '12.0'
  project 'ProjectName.xcodeproj'
  
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # https://github.com/RxReader/alipay_kit/issues/60
#      if target.name == "alipay_kit_ios"
#        config.build_settings["OTHER_LDFLAGS"] = config.build_settings["OTHER_LDFLAGS"] + " -ld_classic"
#      end
#      if target.name == "QCloudCOSXML"
#        config.build_settings["OTHER_LDFLAGS"] = config.build_settings["OTHER_LDFLAGS"] + " -ld_classic"
#      end
#      if target.name == "AlipaySDK-iOS"
#        config.build_settings["OTHER_LDFLAGS"] = config.build_settings["OTHER_LDFLAGS"] + " -ld_64"
#      end
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      # Xcode 14.x, [references](https://darkthanblack.github.io/blogs/02-modularize/)
      # issue: ``SwiftAlgorithms``
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      # issue: ``development team``
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      # issue: ``plist``
      config.build_settings['GENERATE_INFOPLIST_FILE'] = "NO"
    end
  end
end
